<a href="https://colab.research.google.com/github/Akshint0407/Python-Basic-Codes/blob/main/Basic-Python-and-numpy-Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a= np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
b = (0,1,2,3,4,5,6,7,8)

In [ ]:
b[3:5]

(3, 4)

In [ ]:
b[:]

(0, 1, 2, 3, 4, 5, 6, 7, 8)

In [ ]:
a[4:9:2] = 100

In [ ]:
a


array([  1,   2,   3,   4, 100,   6, 100,   8, 100])

In [ ]:
import random as r

In [ ]:
a = np.random.randn(5,2)

In [ ]:
first_name = str("Akshint")
last_name = str("Varma")
print("My name is",first_name,last_name)

My name is Akshint Varma


In [ ]:
  x = 7
  if x < 10:
    print('Less than 10')
    if x > 5:
        print('Greater than 5')
    else:
        print('Less than or equal to 5')

Less than 10
Greater than 5


In [ ]:
while(True):
  bike_price = int(input("Enter the price of the bike"))
  if bike_price > 100000:
      print("15% road tax to be paid")
  elif bike_price > 50000 and bike_price <= 100000:
      print("10% road tax to be paid")
  elif bike_price <= 50000:
      print("5% road tax to be paid")
    else:
      print("Error!")

In [ ]:
age = int(input("Enter your age: "))
gender = input("Enter M or F: ")
if age >= 18 and age < 30:
    if gender == 'M':
        print("You are a young male with Daily Wages = 700")
    else:
        print("You are young female with daily wage = 750")
if age >= 30 and age <= 40:
    if gender == 'M':
        print("You are a middle aged male with daily wage = 800")
    else:
        print("You are a middle aged female with daily wage = 850")

Enter your age: 20
Enter M or FM
You are a young male with Daily Wages = 700


In [ ]:
while(True):
  leap_year = int(input("Enter the year: "))
  if leap_year % 4 == 0:
    if leap_year % 100 == 0:
      if leap_year % 400 == 0:
        print("It is a leap year")
      else:
        print("It is not a leap year")
    else:
      print("It is a leap year")
  else:
    print("It is not a leap year")

In [ ]:
days = int(input("Enter the number of days: "))
if days <= 5:
  print("Cost per day :", days * 2)
elif days <= 10 and days >= 6:
  print("Cost per day :", days * 3)
elif days <= 15 and days >= 11:
  print("Cost per day :", days * 4)
elif days >= 16:
  print("Cost per day :", days * 5)


Enter the number of days: 3
Cost per day : 6


In [ ]:
price_1=0
price_3=0
units = int(input("Enter the no of electric units: "))
if units <= 100:
  print("Free!")
  price = 0
  total_bill = 0
elif units > 100 and units <= 300:
  print("Rs. 2 per unit")
  price_1 = (units - 100) * 2
  total_bill = price_1
elif units > 300:
  print("Rs. 5 per unit")
  price_1 = 200
  price_3 = (units-300) * 5
  total_bill = price_1 + price_3
print("Total Bill: ", total_bill)


Enter the no of electric units: 550
Rs. 5 per unit
Total Bill:  1250


In [ ]:
# Use while(True) to handle the loop
while True:
    # Generate and print even numbers in reverse using the for loop
    for i in range(20, 0, -2):
        print(i, end=" ")
    break  # Exit after the loop completes


20 18 16 14 12 10 8 6 4 2 

In [ ]:
while(True):
  for i in range(20,42,5):
    print(i, end = " ")
  break

20 25 30 35 40 

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,8,3,9,6,8,9,4,6,3,6])
res = (arr > 4) & (arr < 9)
print(arr[res])

[5 8 6 8 6 6]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,8,3,9,6,8,9,4,6,3,6])
print(arr)
copied_arr = arr.copy()
copied_arr[arr%2 == 0] = 0
print(copied_arr)

[1 2 3 4 5 8 3 9 6 8 9 4 6 3 6]
[1 0 3 0 5 0 3 9 0 0 9 0 0 3 0]


In [ ]:
import numpy as np

In [ ]:
a = np.random.randn(3,5)

In [ ]:
print(a)

[[-0.1244332  -0.09921409 -0.43612446 -0.10607034  0.10912878]
 [ 1.9037679  -2.03693862 -0.69518766 -0.29746839 -1.21085253]
 [ 1.09631746 -0.65584884 -0.43706477  0.35729703 -0.04029395]]


In [ ]:
np.mean(a)

-0.17819904552702398

In [ ]:
mean = a.mean()

In [ ]:
print(mean)

-0.17819904552702398


In [ ]:
np.mean(a,axis = 1)

array([-0.13134266, -0.46733586,  0.06408139])

In [ ]:
arr = np.array([1,4,2,7,9,3,5,8,6,10]) #Sorting in Descending order
print(np.sort(arr)[:: -1])

[10  9  8  7  6  5  4  3  2  1]


In [ ]:
arr = np.array([1,4,2,7,9,3,5,8,6,10]) #Sorting in Ascending order
print(np.sort(arr)[::])

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr = np.ones(7)

In [ ]:
print(arr)

[1. 1. 1. 1. 1. 1. 1.]


In [ ]:
x = np.full((3,4),24)

In [ ]:
print(x)

[[24 24 24 24]
 [24 24 24 24]
 [24 24 24 24]]


In [ ]:
np.sum(x)

288

In [ ]:
x = np.random.rand()
print(x)

0.4620834248567036


In [ ]:
string = "python"
for char in string:
    print(char)

p
y
t
h
o
n


In [ ]:
for i in range(5,0,1):
  print(i)

In [ ]:
x = 3
if x == 3 or 4:
  print("yes")
else:
  print("no")

yes


In [ ]:
x = 5
y = 3
z = (x == y)
print(z)

False


In [ ]:
x = 10
y = 3
print(x/y)

3.3333333333333335


In [ ]:
x = 5
y = 10
if x == 5 and not y >20:
  print("yes")
else:
  print("no")

yes


In [ ]:
x = "hello"
if x:
  print("yes")
else:
  print("no")

yes


In [ ]:
a = True
b = False
c = False
print(a or b and c)

True


In [ ]:
x = 1
if x == 1:
  x = 2
elif x == 2:
  x = 3
else:
  x = 4
print(x)

2


In [ ]:
x = 0
for i in range(1, 5):
  x += i
print(x)

10


In [ ]:
a = "hello"
b = "world"
c = " "
d = "python"
e = a + b + c + d
print(e)

helloworld python


In [ ]:
# prompt: square root of positive int simple math opretation code no import

def sqrt_positive_int(n):
  """
  Calculates the square root of a positive integer using simple math operations.

  Args:
    n: A positive integer.

  Returns:
    The integer part of the square root of n.
    Returns -1 if n is negative.
  """
  if n < 0:
    return -1

  if n == 0:
    return 0

  low = 0
  high = n

  while low <= high:
    mid = (low + high) // 2  # Use integer division for whole numbers
    if mid * mid <= n < (mid+1) * (mid+1):
      return mid
    elif mid * mid < n:
      low = mid + 1
    else:
      high = mid -1


In [ ]:
def round_number(number):
    return round(number)

number = float(input("Enter a number: "))

rounded_number = round_number(number)

print("Rounded number:", rounded_number)

Enter a number: 54.98
Rounded number: 55


In [ ]:
a = float(input(" "))
b = float(input(" "))
if a<b:
    print(a)
else:
    print(b)

 6.66
 5
5.0


In [ ]:
limit = int(input("Enter the limit: "))

sum_of_multiples_of_7 = 0
sum_of_multiples_of_8 = 0

for i in range(limit + 1):  # Iterate through numbers from 0 to limit
    if i % 7 == 0:  # Check if i is a multiple of 7
        sum_of_multiples_of_7 += i
    if i % 8 == 0:  # Check if i is a multiple of 8
        sum_of_multiples_of_8 += i

print("Sum of multiples of 7:", sum_of_multiples_of_7)
print("Sum of multiples of 8:", sum_of_multiples_of_8)

Enter the limit: 7
Sum of multiples of 7: 7
Sum of multiples of 8: 0


In [ ]:
def find_factors(num):
    factors = []
    for i in range(1, abs(num) + 1):
        if num % i == 0:
            factors.append((i, num // i))
            if i * i != num:
                factors.append((-i, -num // i))
    factors.sort()
    return factors

num = int(input(""))

factors = find_factors(num)
for factor_pair in factors:
    print(f"{factor_pair[0]} x {factor_pair[1]}")


0


In [ ]:
def find_factors(num):
    if num == 0:
        return [(1, 0)]  # Return (1, 0) for num = 0
    else:
        factors = []
        for i in range(1, abs(num) + 1):
            if num % i == 0:
                factors.append((i, num // i))
                if i * i != num:
                    factors.append((-i, -num // i))
        factors.sort()
        return factors

num = int(input(""))

factors = find_factors(num)
for factor_pair in factors:
    print(f"{factor_pair[0]} x {factor_pair[1]}")

0
1 x 0


In [ ]:
num = int(input("Enter an integer: "))

for i in range(1, abs(num) + 1):
    if num % i == 0:
        print(f"{i} x {num // i}")
        if i * i != num:  # Avoid duplicates for perfect squares
            print(f"{-i} x {-num // i}")

Enter an integer: 0


In [ ]:
def find_factors(num):
    if num == 0:
        return [1]  # Return only 1 for num = 0
    else:
        factors = []
        for i in range(1, abs(num) + 1):
            if num % i == 0:
                factors.append((i, num // i))
                if i * i != num:
                    factors.append((-i, -num // i))
        factors.sort()
        return factors

num = int(input(""))

factors = find_factors(num)

if num == 0:
    print(factors[0])  # Print only 1 for num = 0
else:
    for factor_pair in factors:
        print(f"{factor_pair[0]} x {factor_pair[1]}")

24
-24 x -1
-12 x -2
-8 x -3
-6 x -4
-4 x -6
-3 x -8
-2 x -12
-1 x -24
1 x 24
2 x 12
3 x 8
4 x 6
6 x 4
8 x 3
12 x 2
24 x 1


In [ ]:
import cmath

# Coefficients of the quadratic equation
a = 10
b = -20
c = 30

# Calculate the discriminant
discriminant = (b**2) - 4*(a*c)

# Find the roots using the quadratic formula
x1 = (-b + cmath.sqrt(discriminant)) / (2*a)
x2 = (-b - cmath.sqrt(discriminant)) / (2*a)

# Print the roots using a single print function
print(f"The roots are x1 = {x1} and x2 = {x2}")

The roots are x1 = (1+1.4142135623730951j) and x2 = (1-1.4142135623730951j)


In [ ]:
num = int(input("Enter an integer: "))

if num == 0:
    print(1)  # Special case for 0
else:
    for i in range(1, abs(num) + 1):
        if num % i == 0:
            print(f"{i} x {num // i}")
            if i * i != num:  # Avoid duplicates for perfect squares
                print(f"{-i} x {-num // i}")

Enter an integer: 10
1 x 10
-1 x -10
2 x 5
-2 x -5
5 x 2
-5 x -2
10 x 1
-10 x -1


In [ ]:
import cmath

a = float(input(" "))
b = float(input(" "))
c = float(input(" "))

discriminant = (b**2) - 4*(a*c)

x1 = (-b + cmath.sqrt(discriminant)) / (2*a)
x2 = (-b - cmath.sqrt(discriminant)) / (2*a)

print(x1,x2)

 10
 -20
 30
(1+1.4142135623730951j) (1-1.4142135623730951j)


In [ ]:
a = float(input(" "))
if((a% 4 == 0) and (a % 3 == 0)):
    print("MickeyMouse")
elif a % 4 == 0:
    print("Mickey")
elif a % 3 == 0:
    print("Mouse")
else:
    print(a)

 9
Mouse


In [ ]:
total = float(input(""))
discount = 0
if total < 200:
    print(discount)
elif total <= 500 and total >= 200:
    discount = total - (total * 0.1)
    print(discount)
elif total > 500:
    discount = total - (total * 0.2)
    print(discount)

600
480.0


In [ ]:
def is_prime(n):
    """Returns True if n is a prime number, False otherwise."""
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

limit = int(input(""))
for num in range(2, limit + 1):
    if is_prime(num):
        print(num, end=" ")

10
10
2 3 5 7 

In [ ]:
def is_prime(n):
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
num = int(input())
count = 2
while count <= num:
    if is_prime(count):
        print(count)
        user_input = input()
        if user_input == 'N':
            break
    count += 1

5
2


In [ ]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True
num = int(input())
count = 2
primes_printed = 0

while primes_printed < num:
    if is_prime(count):
        print(count)
        primes_printed += 1
        user_input = input()
        if user_input == 'N':
            break
    count += 1


5
2
Y
3
Y
5
d
7
N


In [ ]:
def is_prime(n):
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
num = int(input())
count = 2
while count <= num:
    if is_prime(count):
        print(count)
        user_input = input()
        if user_input == 'N':
            break
    count += 1

In [ ]:
def hello(name):
    print('Hello ' + name,"How are u")

In [ ]:
hello('akshint')

Hello akshint How are u


In [ ]:
hello("Alice")

Hello Alice How are u


In [ ]:
def fibonacci(N, a=0, b=1):
    counter = 0
    while counter < N:
        a, b = b, a + b
        print(a, end=' ')
        counter += 1

In [ ]:
fibonacci(10)

1 1 2 3 5 8 13 21 34 55 

In [ ]:
fibonacci(10,1,2)

2 3 5 8 13 21 34 55 89 144 

In [ ]:
def square_root(a):
  a = a**0.5 + 1
  print(a)


In [ ]:
square(25)

1


In [ ]:
def val_pp(val):
    return val, val + 1, val + 2

In [ ]:
val_pp(10)

(10, 11, 12)

In [ ]:
r, i, c = val_pp(3)
print(r, i, c)

3 4 5


In [ ]:
r


3

In [ ]:
i

4

In [ ]:
?function-val_pp()

Object `function-val_pp()` not found.


In [ ]:
#Create a function to calculate the cube of a number that is passed as the argument to the function.
def cube(a):
  return a**3

In [ ]:
cube(2)

8

In [ ]:
# Create a function to calculate the sum of squares of 2 numbers that are defined as the default arguments, resulting in a square output of 5.

def sum_of_squares(a=2, b=3):
  return a**2 + b**2


In [ ]:
sum_of_squares(5,0)

25

In [ ]:
#Create a function to calculate the factorial of a number passed as an argument and assign the output of the function to a variable named out.
def factorial(n):
  result = 1
  for i in range(1, n + 1):
    result *= i
  return result

In [ ]:
factorial(3)

6

In [ ]:
# prompt: #Create a function to calculate the area of a triangle or rectangle using 3 arguments: base, height, and shape.

def calculate_area(base, height, shape):
  if shape == str("triangle"):
    return 0.5 * base * height
  elif shape == str("rectangle"):
    return base * height
  else:
    return None

In [ ]:
area(10,5,"triangle")

25.0

In [ ]:
#Create a function that returns a None value and displays the result of string concatenation. Take the 2 strings required for the function as arguments as shown below.
def concatenate_strings(str1, str2):
  print(str1 + str2)
concatenate_strings("hello", "world")

helloworld


In [ ]:
concatenate_strings("","")

In [ ]:
#n: 1 + 1/1! + 1/2! + 1/3! + + 1/n!
n = int(input())
total_sum = 0
for i in range(n + 1):
  total_sum += 1 / factorial(i)
print(total_sum)

2
2.5


In [ ]:
sum(1)

1.0

In [ ]:
def is_pangram(text):
  text = text.lower()
  alphabet = "abcdefghijklmnopqrstuvwxyz"
  for char in alphabet:
    if char not in text:
      return False
  return True

# Get input from the user
text = input("Enter a string: ")

# Check if the string is a pangram and print the result
if is_pangram(text):
  print("The string is a pangram.")
else:
  print("The string is not a pangram.")

Enter a string: c
The string is not a pangram.


In [2]:
def greet():
    print("hey")
greet

<function __main__.greet()>

In [ ]:
def multiply(a,b=2):
  return a*b

result1 = multiply(3)
result2 = multiply(4,5)
print(result1)
print(result2)

6
20


In [ ]:
def square(num):
  return num**2

In [ ]:
def concatinate_strings(*arg):
  result = ""
  for string in arg:
    result += string
  return result
a = "hello"
b = "world"
concatinate_strings(a,b)

'helloworld'

In [ ]:
print('Hello World!')

Hello World!
